version: '3.8'

services:
  backend:
    build: ./backend
    container_name: recipe_backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: recipe_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend

  redis:
    image: redis:7.0-alpine
    container_name: recipe_redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
